sudo: required
dist: xenial
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
  - secure: G61WoWCNhltHyNJyp525jETKc1dAGy9vlv60VXE2i7f80wy/ZELTV0yJK1jfDQH8JGcHz05PRXabgJPUPmVpHZUwI2DarFMI71RTddvXCqE7+6JiWzMTQ01CX8vf7A3UNzOclpQoxrtPGGJRPvs43QSi6kil85GI6tFz4jwjF4FuiB90ZfiQYFeF5QrZRxb3mqqhylY7zUwax2xUzAuXa+6kOtWaZ4nMDB19b0qyniW+t+Z8l1EJXydlkJTAJ+8l9qKaefiVIBfAbuCmBEqmoFwTghQVBX2tXK7cSjUD4rrGcW6JsQONhWbLA+g9eqpfO3UZ2j9jFSwgEf5Ztlt0pIpOZP0RQkl7gbWZkagSlgKTipooNTTOLk0CXqIIsOpw6LnmxcTrK/Ddr578MhOuwUAIw0Qn9ocRFsbOiVG4eBm7LCllEFBdk2Zv3jGOtyJMsoUWoV6x5Ytf6YL34smjd7qZL8yoIkAfTWl6BMYFDi3sOkxXHWeDerolOv4EZ/GwJdriyLolISKaPTI37zqTCy04lmFvEzJ2y/fxpTBAEd7HPEJgQAbBCVwPTipd33ZTs29J36DEwnSmtJS1ed79iU+HLGbnTGBe+wwodM16Xn5jiYwzJ8Yfiq0oMPrQ2LviIRWFlX9Xq+YsySUUItWz2jlnVHyVmePfCBBLMN4/wzg=
script: make
deploy:
  provider: script
  script: make release || travis_terminate 1
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    secure: Y//gW9PBbuVPfzl1+B/p3LvOVv1l2Pl95u/NltGmLJFbfnPfKooPyc3rXMHefV+HiJpTd7LTqr5Em30ylK8+DsfFf/eykA+oE6rC8tCjWBe8vdZs53ieKCg/y1u5B9onVjOJZV/7vc+HdOt2NFzMG0/1zHR6C+Sd7ubsQUbHjXMIc48LrfYpgQzgec6DQXpL0Kcp0dw65FfhVy65bqIqKMlVTuTE+gE4GRm7fYG+SJ28ecs1iFFA8fjEF3tRIKVy40j+O0PUFQ3iLPDrqud0fWavj9YiHg/1Pfa8pgqLKuP3kvMIIrAqNofuqNNU1JzD4CP1NgmY2o8+wB5Krt9/N7VUg6B0whJyZ/Dc49Clefeak6vxMWOTZGHrE07kOJtkGf/iyBuu6FeY3FOH8noaTDkCF1PP9UH40Z8AWFxXs3gevn6lj5LPcRy7EDrP+FRwOyksxPO6uQl1x3IV86+ZAsbHnH0C2Hz1IZ8jcl19EUCB1FMiJsrtFWu72pZXhM8LGW04AexK6cXNrQl2qGzVA1guRcL0v4dNFYmNFJt4wEAF4MuKu4rYOYm8ovQtQ6ZYXk50d8aWLeG1P7+sLk1HkyKeEp5VqzO4HAkl3pMSAux2N9VowYCBwyDmxQWSwJRs+xO7yFOjNBv51ziRZ/3uNereCLPZD8filQYtjMcAoXE=
